version: '3.8'

services:
  interacties:
    image: minisungam/interacties:latest
    container_name: interacties
    restart: unless-stopped
    ports:
      - "5500:5500"
    volumes:
      - ./config.json:/app/config.json